### ISSUE TITLE
Simple way to disable all dynamic-ness

### ISSUE THREAD

**Issue by rpitasky** [andreasKroepelin/typst-slides#22]
It would be nice to be able to export all of my slides with all of the dynamic content rendered as if it was static; I like to post my slides after I give my presentations, and it's inconvenient for people looking at them later.

**Comment by andreasKroepelin** [comment]
I think it is called handout in beamer, right? Definitely an important feature.

Things to think about:

If a slide contains no `only` or `alternatives`, we can just ignore all dynamic commands. So maybe, say, `uncover` checks if it is in handout mode and then just spits out its content without any magic.
However, what to do with a slide containing `#only("2-")[abc] #only(3)[def]` or `#alternatives[abc][def]`? I guess then handout mode has to behave identically to presentation mode, otherwise the result wouldn't make sense (think of the [ice cream example](https://andreaskroepelin.github.io/typst-slides/book/dynamic.html#alternatives-to-substitute-content) in the book).

The less trivial questions is what to do when a slide contains both `only` and `uncover`. Should the `uncover` be disabled but the `only` not?

**Comment by andreasKroepelin** [comment]
Also, I'm thinking of an API of the form
```typ
#show: slides.with(
    // ...
    handout: true,
)
```

Any opinions on that?

**Comment by rpitasky** [comment]
Any particular reason not to add another option to cover-mode, i.e.
cover-mode-handout?

**Comment by Holt59** [comment]
> Any particular reason not to add another option to cover-mode, i.e. cover-mode-handout?
> 
You mean per `#uncover`, etc.? I think the idea here is to have a global option because you want to be able to generate both the dynamic and the static PDF without having to modify every covered content.

**Comment by Holt59** [comment]
Since this is WIP feature, I think it'd be nice to have a way to disable "split" a slide when doing handout, e.g., if a slide has 8 steps, being able to put the "state" of the slide at step 3, 5 and 8 in separate slides.

A typical use-case I encounter in Beamer is when you have a slide with 2 columns, where one column is static and you show various contents on the other (e.g., 2 or 3 examples). In that case, handout in Beamer only keep the last example, so I often find myself having to duplicate the slide 3 times while only changing the second column.

**Comment by andreasKroepelin** [comment]
> A typical use-case I encounter in Beamer is when you have a slide with 2 columns, where one column is static and you show various contents on the other (e.g., 2 or 3 examples). In that case, handout in Beamer only keep the last example, so I often find myself having to duplicate the slide 3 times while only changing the second column.

That's the thing I was thinking about regarding `#alternatives`, right?

**Comment by Holt59** [comment]
> > A typical use-case I encounter in Beamer is when you have a slide with 2 columns, where one column is static and you show various contents on the other (e.g., 2 or 3 examples). In that case, handout in Beamer only keep the last example, so I often find myself having to duplicate the slide 3 times while only changing the second column.
> 
> That's the thing I was thinking about regarding `#alternatives`, right?

Ah yes, looks like it.

**Comment by rpitasky** [comment]
> > Any particular reason not to add another option to cover-mode, i.e. cover-mode-handout?
> 
> You mean per `#uncover`, etc.? I think the idea here is to have a global option because you want to be able to generate both the dynamic and the static PDF without having to modify every covered content.

When I last used typst-slides, cover-mode was global. My apologies.
